### ISSUE TITLE
Big Man Boogie is a temporary replacement for Keep on rolling (bring it back, maybe?)

### ISSUE THREAD

**Issue by Wuzzy2** [OpenTTD/OpenMSX#12]
In the changelog I have found this:

> - Fix #1202: Replace 'Keep on rolling' (temporarily) with 'Big Man Boogie' by Jim Redfarn

The “#1202” here is referring to this: https://dev.openttdcoop.org/issues/1202

So, as far I know, the track 'Keep on rolling' once was part of OpenMSX before, but had to be removed due to a bug (crash in Windows). This sounds like it was planned to bring back Keep on rolling eventually, but this has never happened / forgotten.

So I have listened to both tracks now. Personally, I think the 'Keep on rolling' track is way better compared to the other one, and I would love to have it back, so I would love to see 'Keep on rolling' going back into OpenMSX.

Thankfully, DevanWolf seems to have posted a supposedly fixed version of this song in the chaotic PR #1 (not tested, however). Here is the link to the file: https://github.com/OpenTTD/OpenMSX/blob/a94a5b9a7b8fb870fa5402a4d599fe1e54ddbed4/src/keep_on_rolling.mid

What do you think? Should we actually bring back Keep on rolling?

**Comment by orudge** [comment]
https://www.tt-forums.net/viewtopic.php?p=1220145#p1220145 has a bit more information it seems on the updates.

**Comment by orudge** [comment]
With regards to bringing back this song, I have no particular issue with doing that; we may want to check if it works without crashing OpenTTD 1.0.0 using the MCI driver (i.e., has a fix in the song sorted it, or has a change in OpenTTD sorted it).
