### ISSUE TITLE
OpenMSX does not work on OpenTTD 14.0-RC2

### ISSUE THREAD

**Issue by sonkagen** [OpenTTD/OpenMSX#34]
Is it not ready for new version?
I installed the OpenTTD 14.0-RC2 by homepage and the other three base sets, graphics and sound got work but only OpenMSX not yet. For comforming it I also installed 13.4 the stable. In this time it did work as expect.
I'm not good to English. That's my rare time use github, first time to acknowledge the OpenTTD as well. Hope to make sense.

**Comment by PeterN** [comment]
Can you try installing OpenMSX from the in-game content downloader instead of from the homepage and see if that works?

**Comment by sonkagen** [comment]
I see it. Thanks a lot.
