### ISSUE TITLE
Release new version with py3 support

### ISSUE THREAD

**Issue by matthijskooijman** [OpenTTD/OpenMSX#4]
I noticed that py3 support was added to master last month. Any chance this can be included in a new release soon? Debian is in the process of removing Python2, so without py3 support, OpenMSX will be removed in the near future. I might try backporting the py3 changes, but here have been some other build system changes, so I'm not sure if that will just work.

**Comment by matthijskooijman** [comment]
Probably still good to release, but for Debian I've ended up backporting 95ae6129c9c2edcaa79d49117aee8b172d20e8a8 and ffb7cb7f597b92d506f744c707c2c0d4cf3029fd which together make the build work on Python3, so no more hurry from my side.

**Comment by Wuzzy2** [comment]
Can you please specify which script files specifically are incompatible with Python 3 and why?

To me, it seems all Python scripts are compatible with Python 3 now; it builds just fine to me.

Also, I think it would make sense to treat “py3 support” and “release new version” as two separate issues.

**Comment by orudge** [comment]
> To me, it seems all Python scripts are compatible with Python 3 now; it builds just fine to me.

Python 3 support was added in https://github.com/OpenTTD/OpenMSX/commit/ffb7cb7f597b92d506f744c707c2c0d4cf3029fd

**Comment by Wuzzy2** [comment]
I see, it seems this issue is actually just about making a release then.

In that case, I want to note that there are still a couple of things that should be fixed in OpenMSX, like the outdated build system with Mercirual references, or the outdated README file.

Speaking of releases, I suggest that when all problems in OpenMSX are fixed, go straight for version 1.0.0. OpenMSX has been de facto finished for years, there is no point in false humility. ;-)

**Comment by matthijskooijman** [comment]
> I see, it seems this issue is actually just about making a release then.

Yup, py3 support is only the reason for wanting a release, not something left to fix :-)

> In that case, I want to note that there are still a couple of things that should be fixed in OpenMSX, like the outdated build system with Mercirual references, or the outdated README file.

Per you own logic (which I agree with), these should probably be separate issues. Looking at the issue list, it seems you already created issues, so I guess your question really is: "Can we fix #5 and #6 before release?"

**Comment by Wuzzy2** [comment]
I don't really mind if the release would be done without the other fixes, as long they will be fixed (and released) *eventually*. PRs are already in the pipeline for that, after all.

But a release without a functional up-to-date build scripting should probably not be 1.0.0.

**Comment by orudge** [comment]
You *can't* have a release until the building scripting is modernised, it's a prerequisite. :)

But given it has been done for OpenSFX, it shouldn't be hard to get it working for OpenMSX too. I'm a bit busy at the moment but when I get a chance I'll take a look at it if nobody's beaten me to it first. (Feel free to volunteer!)

**Comment by Wuzzy2** [comment]
Concerning the build system: #7 #8

**Comment by LordAro** [comment]
Issue resolved. New release following shortly
